// From the SULI poster ("Rxn Bench: A Low-Cost Lab-Automation Platform", 2026) and the project
// README in github.com/RxnRover/automated_chem_bench. The poster is the source of truth for credits.
export default {
  title: "Rxn Bench",
  subtitle: "A low-cost lab-automation platform · SULI internship, Ames National Laboratory",
  category: "lab-automation",
  date: "2026-06",
  dateLabel: "Summer 2026",
  featured: true,
  order: 1,
  summary: "A low-cost, modular lab-automation platform built from a repurposed 3D printer, with pH sensing, swappable toolheads, and a desktop control app.",
  cover: "/images/projects/rxn-bench/assembled-1.jpg",
  description: [
    "Rxn Bench is a DIY automated chemistry bench. A Sovol SV08 3D printer is repurposed as the XYZ motion platform, with a pipette toolhead for aspirating and dispensing liquid and an Atlas Scientific probe for pH sensing.",
    "A Raspberry Pi on the printer runs Klipper and Moonraker plus SiLA2 device servers for the gantry and the pH sensor. A separate operator machine runs the Rxn Bench desktop app, which talks to those servers over gRPC/SiLA, and experiment scripts drive the bench through a Python client.",
    "I built it during my [SULI internship](https://science.osti.gov/wdts/suli) at Ames National Laboratory, alongside the lab's [RxnRover](/work/rxn-rover/) lab automation platform.",
  ],
  role: "Co-author and project lead for the platform: software development, system design, hardware design, fabrication, and integration.",
  video: { youtube: "TYSwPctkNtk", aspect: "16/9", title: "Rxn Bench in action: automated pH calibration and measurement" },
  problem: "Lab automation hardware is expensive and usually tied to one vendor. Rxn Bench aims to be a lower-cost foundation for automated experimentation and high-throughput data collection: accessible hardware, a modular architecture, and a pre-built software stack and 3D models that other labs can adapt.",
  results: [
    "Demonstrated: automated two- and three-point pH-probe calibration, and automated measurement of more than 24 samples without continuous manual operation, on hardware costing under $1,000.",
    "Devices are integrated by capability rather than specific hardware, so similar devices from different vendors drop in, and \"mock\" devices allow remote testing and development.",
  ],
  details: [
    "XYZ motion: a Sovol SV08 CoreXY printer running Klipper, controlled through the Moonraker API.",
    "Liquid handling: a pipette cone assembly whose plunger is driven by a stepper linear actuator.",
    "pH sensing: an Atlas Scientific EZO pH circuit on an electrically isolated carrier board, with a spear-tip probe in a 3D-printed toolhead.",
    "Tool changing: toolheads dock on the gantry through a 3D-printed mount with linear rails.",
    "Control: SiLA2 device servers on a Raspberry Pi 5, a desktop UI with gantry, pH sensor, and experiment-runner widgets, and a Python client for experiment scripts.",
    "Labware: a 3D-printed workspace with a spill catcher and magnetic footprints for standard 6-, 15-, 24-, and 96-well plates.",
    "Future work: multi-toolhead operation, automated liquid handling, closed-loop self-driving experiments, and AI-assisted device integration.",
  ],
  tools: ["Python", "SiLA2 / gRPC", "Klipper", "Moonraker", "Raspberry Pi 5", "Sovol SV08", "Atlas Scientific EZO pH", "CAD", "Bambu Lab A1 3D printer"],
  skills: ["Lab automation", "Embedded systems", "Hardware design", "3D printing and fabrication", "System integration"],
  images: [
    { src: "/images/projects/rxn-bench/poster.jpg", alt: "Research poster: Rxn Bench, A Low-Cost Lab-Automation Platform, with system design, interface, workflow, 3D-printed tools, and results", caption: "SULI research poster, 2026" },
    { src: "/images/projects/rxn-bench/assembled-1.jpg", alt: "The assembled Rxn Bench with the pipette toolhead positioned over a well plate", caption: "Assembled bench" },
    { src: "/images/projects/rxn-bench/assembled-2.jpg", alt: "Rxn Bench running on a lab bench next to the operator laptop showing the desktop UI", caption: "Running next to the operator UI" },
    { src: "/images/projects/rxn-bench/system-block-diagram.png", alt: "System block diagram: the operator UI talks to the Raspberry Pi's SiLA server, which drives the SV08 controller, an onboard camera, and the EZO pH circuit and probe", caption: "System block diagram" },
    { src: "/images/projects/rxn-bench/ph-toolhead-cad.jpg", alt: "CAD render of the pH probe toolhead, cut away to show the EZO pH circuit board inside", caption: "pH toolhead, CAD" },
    { src: "/images/projects/rxn-bench/ph-toolhead-assembled.jpg", alt: "The assembled 3D-printed pH probe toolhead", caption: "pH toolhead, assembled" },
    { src: "/images/projects/rxn-bench/docking-mount-cad.jpg", alt: "CAD render of the toolhead docking mount with linear rails", caption: "Docking mount, CAD" },
    { src: "/images/projects/rxn-bench/docking-mount-assembled.jpg", alt: "The 3D-printed toolhead docking mount held in hand", caption: "Docking mount, printed" },
    { src: "/images/projects/rxn-bench/ui-main.jpg", alt: "Rxn Bench desktop UI showing the gantry workspace, pH readout, and experiment runner", caption: "Desktop UI" },
    { src: "/images/projects/rxn-bench/ui-add-device.jpg", alt: "Rxn Bench desktop UI add-device view", caption: "Adding a device" },
    { src: "/images/projects/rxn-bench/logo.png", alt: "Rxn Bench logo: a gantry pipetting into a well plate", caption: "Logo" },
  ],
  credits: [{ role: "Funding", name: "U.S. Department of Energy, Office of Science (SULI program)" }],
  collaborators: [
    { name: "Felisha Kuo", role: "Co-author (SULI intern)" },
    { name: "Lun An", role: "Research mentor" },
    { name: "Zachary Crandall", role: "Research mentor" },
    { name: "David Lee", role: "Acknowledged: logistics and feedback" },
    { name: "Long Qi", role: "Acknowledged: early conceptual input" },
  ],
  links: [
    { label: "Rxn Bench app (GitHub)", url: "https://github.com/RxnRover/RxnBench" },
    { label: "Bench hardware & servers (GitHub)", url: "https://github.com/RxnRover/automated_chem_bench" },
    { label: "Demo video", url: "https://www.youtube.com/watch?v=TYSwPctkNtk" },
    { label: "SULI program", url: "https://science.osti.gov/wdts/suli" },
    { label: "Ames National Laboratory", url: "https://www.ameslab.gov" },
  ],
  documents: [{ label: "SULI research poster", file: "/documents/research/RxnBench_SULI_Poster_2026.pdf" }],
};
