// From the "This Website" card on the previous site (origin/main), updated for the redesign.
export default {
  title: "This Website",
  category: "software",
  order: 14,
  summary: "The portfolio site you're looking at right now, built from scratch.",
  cover: "/images/projects/website-icon.png",
  description: [
    "A static personal portfolio built from scratch: hand-written HTML, CSS, and JavaScript templates generated by a small Node build script, with a responsive image pipeline, a keyboard- and swipe-friendly full-screen gallery, category filters, click-to-load video, and custom audio players. Everything still works without JavaScript.",
    "The previous version was a single-page résumé with a tabbed project gallery, an accessible lightbox, a rotating featured-projects carousel, and a skill-tag system that jumped to the projects showcasing each skill.",
  ],
  role: "Sole developer: designed and built the entire site, layout, and interactive features from scratch.",
  skills: ["HTML", "CSS", "JavaScript", "Responsive design", "Static site generation", "Image optimization"],
  tools: ["Node.js", "sharp", "Vanilla JavaScript"],
  images: [{ src: "/images/projects/website-icon.png", alt: "HTML5 logo representing this website" }],
  links: [{ label: "GitHub repository", url: "https://github.com/JohnBrittaein/resume-website" }],
};
